{% set name = "ugly_csv_generator" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ugly_csv_generator-{{ version }}.tar.gz
  sha256: 6e5f0530e05bd6cd18e364f443faaa0d2110c3fa137e2835fd2fc1cfb62cc02d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas >=2.1.0
    - numpy
    - tqdm

test:
  imports:
    - ugly_csv_generator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LucaCappelletti94/ugly_csv_generator
  summary: Python package to generate ugly real-looking csvs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
